### ISSUE TITLE
Event Number Checking in event builder

### ISSUE THREAD

**Issue by simonspa** [eudaq/eudaq#149]
This needs to be discussed: currently our event mismatch checker only triggers on mismatches >= 2 events and has some weird extra cases for TLU events at startup:

```
      if ((m_buffer[i].events.front()->GetEventNumber() != m_eventnumber) && (m_buffer[i].events.front()->GetEventNumber() != m_eventnumber - 1)) {
          if (ev.GetEventNumber() % 1000 == 0) {
            // dhaas: added if-statement to filter out TLU event number 0, in case of bad clocking out
            if (m_buffer[i].events.front()->GetEventNumber() != 0)
              EUDAQ_WARN("Event number mismatch > 1 in event " + to_string(ev.GetEventNumber()) + " " + to_string(m_buffer[i].events.front()->GetEventNumber()) + " " + to_string(m_eventnumber));
            if (m_buffer[i].events.front()->GetEventNumber() == 0)
              EUDAQ_WARN("Event number mismatch > 1 in event " + to_string(ev.GetEventNumber()));
          }
```
from: https://github.com/eudaq/eudaq/blob/v1.5-dev/main/lib/src/DataCollector.cc#L162

This does not seem to be right to me, we should be more strict here IMHO.

I see spurious problems in some runs with two CMS Pixel devices where there seems to be some sort of event shifting. The really weird thing about this is, that the OnlineMonitor shows perfect correlation between all devices (MIMOSA <-> MIMOSA, MIMOSA <-> CMS, CMS <-> CMS) while after conversion to SLCIO the EUTelescope Correlator processor produces plots where correlation is only seen between the MIMOSA detectors, but not with the CMS devices.
If this problem appears, all consecutive runs have the same problem. A restart of EUDAQ and reconfiguration of the hardware usually solves this. But the bad thing is, it requires offline analysis of the data to encounter the problem.

Also, I don't see how online monitoring and LCIO conversion should be different from one another since there should only be one RawEvent in the same buffer at a time rendering event shifting or memory f**ups impossible.

I don't know if this is necessarily connected to the above finding.
Any ideas very welcome.

Notify: @stanitz @RPeschke @dreyling @TCThenna

**Comment by simonspa** [comment]
Attached are two plots, both produced seconds ago from the same EUDAQ raw file with the following procedures:

* EUDAQ: ./binOnlineMonitor.exe -sc 1 -f ../data/run020202.raw
![screenshot from 2015-07-09 16 22 37](https://cloud.githubusercontent.com/assets/1677436/8597683/2a1b748c-2657-11e5-9392-eeba248633e9.png)

* EUTelescope: same EUDAQ installation, Native Reader to LCIO, then Clustering & Correlator
![screenshot from 2015-07-09 16 23 47](https://cloud.githubusercontent.com/assets/1677436/8597692/33920792-2657-11e5-8d10-237beb35b37e.png)

Both show correlation plots for the X axis of plane 3 and 7 (which happen to be next to each other geometrically).

In the Onlinemon you see perfect correlation (never mind the negative slope, we are rotated) while in the EUTelescope correlator you only see uniform nothing.

**Comment by RPeschke** [comment]
Hi,


try it with EUDAQ 2 (rpeschke/SyncBase_forDataCollector_based_On_EUDAQ2dev)  and overload the isSyncWithTLU function to fit your needs. 



you can also try this brunch (rpeschke/Processor_class) but it has some unclean code in it…



Gruss,

Richard 





From: simonspa
Sent: ‎Thursday‎, ‎July‎ ‎9‎, ‎2015 ‎4‎:‎26‎ ‎PM
To: eudaq/eudaq
Cc: RPeschke





Attached are two plots, both produced seconds ago from the same EUDAQ raw file with the following procedures:

EUDAQ: ./binOnlineMonitor.exe -sc 1 -f ../data/run020202.raw
 screenshot from 2015-07-09 16 22 37 


EUTelescope: same EUDAQ installation, Native Reader to LCIO, then Clustering & Correlator
 screenshot from 2015-07-09 16 23 47 


Both show correlation plots for the X axis of plane 3 and 7 (which happen to be next to each other geometrically).

In the Onlinemon you see perfect correlation (never mind the negative slope, we are rotated) while in the EUTelescope correlator you only see uniform nothing.

**Comment by simonspa** [comment]
But this would solely be for new data taken online, right? Do I have any further possibility to solve the riddle with already recorded data? Because the plots above are reproducibly with the files only - just running OnlineMon or NativeReader on them...

**Comment by RPeschke** [comment]
no you could just use the converter to create a set of resync events and store them again as a raw file. there is also a compiler flag which forces EUDAQ2 to output EUDAQ1 files. that way you can continue working with EUDAQ 1 code

**Comment by simonspa** [comment]
@RPeschke after a really painful merge I managed to finally compile this together with the converter plugins I need. However, when running the converter it immediately segfaults:

```
./Converter.exe -t native 20202

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fb3d894b84a in __GI___waitpid (pid=8853, stat_loc=stat_loc
entry=0x7fffc046fd00, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:31
#1  0x00007fb3d88c4ffb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007fb3d7ef53b3 in TUnixSystem::StackTrace() () from /opt/root/lib/libCore.so
#3  0x00007fb3d7ef709c in TUnixSystem::DispatchSignals(ESignals) () from /opt/root/lib/libCore.so
#4  <signal handler called>
#5  StartRun (this=0x7fffc0472500) at /home/spanns/ilcsoft/eudaq/./main/include/eudaq/readAndProcessDataTemplate.h:78
#6  main (argv=0x7fffc0472738) at /home/spanns/ilcsoft/eudaq/main/exe/src/Converter.cxx:46
===========================================================

```
